# Generated by Django 5.2.7 on 2025-10-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('revenue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendapatan',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendapatan', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='pendapatan',
            name='mitra',
            field=models.ForeignKey(limit_choices_to={'role': 'mitra'}, on_delete=django.db.models.deletion.CASCADE, related_name='pendapatan', to=settings.AUTH_USER_MODEL),
        ),
    ]
