# Generated by Django 5.2.7 on 2025-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendapatan',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
