# Generated by Django 5.2.7 on 2025-10-23 05:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pendapatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='court',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sportscategory'),
        ),
        migrations.AddField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
