# Generated by Django 5.2.7 on 2025-10-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_create_dummy_mitra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitra',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mitra',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
