# Generated by Django 5.2.7 on 2025-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_court_image_and_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='court_images/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='facility_icons/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='sportscategory',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='venue_images/'),
        ),
    ]
