# Generated by Django 5.2.7 on 2025-10-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_increase_image_field_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='backend.court')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('court', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='backend.courtsession'),
        ),
    ]
