# Generated by Django 5.2.7 on 2025-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_courtsession_booking_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='image',
        ),
        migrations.AddField(
            model_name='courtimage',
            name='image_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venueimage',
            name='image_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
