# Generated by Django 5.2.7 on 2025-10-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venues.sportscategory'),
        ),
        migrations.AddField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='courtimage',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courts.court'),
        ),
        migrations.AddField(
            model_name='courtsession',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courts.court'),
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('venue', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='courtsession',
            unique_together={('court', 'start_time')},
        ),
    ]
